### PR TITLE
Stripping implementation

### PR DESCRIPTION
**Pull request by fatroom**
This PR is proposal to strip implementation to give template for thinking on mars rover kata in TDD way.

### CODE REVIEW

**Comment by fatroom** [comment]
If you going to accept this PR then it would be nice to make a branch with already implemented solution before.

**Comment by vfarcic** [comment]
What do you think about making a separate branch with stripped version and leave the solution in the master? I can update article links and README with links to master (full solution) and branch with stripped version.

In any case, thank you for the pull request. I'll merge it to the master or a separate branch later (I'm currently in the office with a client).

**Comment by fatroom** [comment]
Not sure about merging this to separate branch. It's looks like providing puzzle book where solution is  printed before the actual puzzle.

**Comment by n2o** [comment]
I'd join @fatroom's opinion. Since Katas are for learning purposes, the default approach should be to show the skeleton instead of showing the solution first.

**Comment by vfarcic** [comment]
@fatroom You're probably right. However, the problem is that it is already referenced in a couple of articles (maybe a book as well) and I'm afraid that merging this to master would break a few things. It would be easy if I could identify where those references are. However, a few years passed and my memory does not serve me that well.

**Pull request closed without merging**
